<?php
return array(
'DEFAULT_ADMIN'=>'admin',
'URL_MODEL'=>'0',
'AUTH_KEY'=>'fanwe',
'TIME_ZONE'=>'8',
'ADMIN_LOG'=>'1',
'DB_VERSION'=>'方舟1.0',
'DB_VOL_MAXSIZE'=>'8000000',
'WATER_MARK'=>'',
'SITE_FOOT_MY'=>'<a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a>',
'BIG_WIDTH'=>'500',
'BIG_HEIGHT'=>'500',
'SMALL_WIDTH'=>'200',
'SMALL_HEIGHT'=>'200',
'WATER_ALPHA'=>'75',
'WATER_POSITION'=>'4',
'MAX_IMAGE_SIZE'=>'3000000',
'ALLOW_IMAGE_EXT'=>'jpg,gif,png',
'BG_COLOR'=>'#ffffff',
'IS_WATER_MARK'=>'1',
'TEMPLATE'=>'fanwe',
'SITE_LOGO'=>'./public/attachment/201308/28/16/521db7a95e082.jpg',
'SEO_TITLE'=>'.',
'REPLY_ADDRESS'=>'info@fanwe.com',
'MAIL_ON'=>'1',
'SMS_ON'=>'0',
'PUBLIC_DOMAIN_ROOT'=>'',
'APP_MSG_SENDER_OPEN'=>'0',
'ADMIN_MSG_SENDER_OPEN'=>'0',
'GZIP_ON'=>'0',
'SITE_NAME'=>'方舟网',
'CACHE_ON'=>'1',
'EXPIRED_TIME'=>'0',
'TMPL_DOMAIN_ROOT'=>'',
'CACHE_TYPE'=>'File',
'MEMCACHE_HOST'=>'127.0.0.1:11211',
'IMAGE_USERNAME'=>'admin',
'IMAGE_PASSWORD'=>'admin',
'DEAL_MSG_LOCK'=>'0',
'SEND_SPAN'=>'2',
'TMPL_CACHE_ON'=>'1',
'DOMAIN_ROOT'=>'',
'COOKIE_PATH'=>'/',
'INTEGRATE_CFG'=>'',
'INTEGRATE_CODE'=>'',
'PAY_RADIO'=>'0.1',
'SITE_LICENSE'=>'方舟网 - fzhou.com 版权所有',
'SEO_KEYWORD'=>'SEO关键词',
'SEO_DESCRIPTION'=>'SEO描述',
'PROMOTE_MSG_LOCK'=>'0',
'PROMOTE_MSG_PAGE'=>'0',
'SITE_FOOT_DESC'=>'方舟网是一个由LOGO与网站的简易介绍语加标签组成。标签：隐私权政策，服务条款。请随机填充一些标签上去。',
'SITE_FOOT_QUESTION'=>'<a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a>',
'SITE_FOOT_PROJECT'=>'<a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a><a href=\"#\">联系我们</a>',
'SITE_FOOT_WAY'=>'<a href=\"#\"><img src=\"./app/Tpl/fanwe/images/weibo.jpg\" /></a><a href=\"#\"><img src=\"./app/Tpl/fanwe/images/weixin.jpg\" /></a><a href=\"#\"><img src=\"./app/Tpl/fanwe/images/douban.jpg\" /></a><a href=\"#\"><img src=\"./app/Tpl/fanwe/images/cboke.jpg\" /></a><a href=\"#\"><img src=\"./app/Tpl/fanwe/images/cother.jpg\" /></a>',
);
 ?>